name: Smoke gamelogs via CMS JSON

on:
  workflow_dispatch:
    inputs:
      season:
        description: "Season (e.g. 2025)"
        required: true
        default: "2025"
      competition:
        description: "E or U"
        required: true
        default: "E"
      mode:
        description: "statisticMode"
        required: true
        default: "perGame"
      player_code:
        description: "Optional player_code (for tagging rows)"
        required: false
        default: ""
      json_url:
        description: "CMS JSON URL (single player) — leave empty if using json_file"
        required: false
        default: ""
      json_file:
        description: "Path to local CMS JSON file (e.g. in/003458.json)"
        required: false
        default: "in/003458.json"
      out_dir:
        description: "Output folder"
        required: true
        default: "out"

jobs:
  probe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      - name: Run CMS gamelog parser (single player)
        run: |
          python cms_probe.py \
            --season "${{ github.event.inputs.season }}" \
            --competition "${{ github.event.inputs.competition }}" \
            --mode "${{ github.event.inputs.mode }}" \
            --player-code "${{ github.event.inputs.player_code }}" \
            --json-url "${{ github.event.inputs.json_url }}" \
            --json-file "${{ github.event.inputs.json_file }}" \
            --out "${{ github.event.inputs.out_dir }}"

      - name: List outputs
        run: ls -lah "${{ github.event.inputs.out_dir }}" || true
